dataset:
  budget: 2000
  initial_points_per_class: 20
  classifier_batch_size: 48
  validation_split: 0.04

classifier:
  type: Resnet18

optimizer:
  type: NAdam
  lr: 0.001
  weight_decay: 0.0

dataset_embedded:
  encoder_checkpoint: encoder_checkpoints/cifar10_27.03/model_seed1.pth.tar
  budget: 350
  initial_points_per_class: 1
  classifier_batch_size: 64

classifier_embedded:
#  type: MLP
#  hidden: [24, 12]
  type: Linear

optimizer_embedded:
  # Linear
  type: NAdam
  lr: 0.00171578341563099
  weight_decay: 2.38432342659786E-05
  # MLP
#  type: Adam
#  lr: 0.00422210204014432
#  weight_decay: 1.62121435184421E-08

# Pretext Task (SimCLR)
pretext_encoder:
  type: Resnet18
  feature_dim: 128

pretext_optimizer:
  type: SGD
  lr: 0.4
  nesterov: False
  weight_decay: 0.0001
  momentum: 0.9
  lr_scheduler: cosine
  lr_scheduler_decay: 0.1

pretext_clr_loss:
  temperature: 0.1

pretext_training:
  batch_size: 512
  epochs: 500
