dataset:
  budget: 1000
  initial_points_per_class: 1
  classifier_batch_size: 64
  validation_split: 0.04

classifier:
  type: Resnet18

optimizer:
  type: NAdam
  lr: 0.001
  weight_decay: 0.0

dataset_embedded:
  encoder_checkpoint: TODO
#  encoder_checkpoint: encoder_checkpoints/fashion_mnist_17.04/model_seed1.pth.tar
  budget: 500
  initial_points_per_class: 1
  classifier_batch_size: 64

classifier_embedded:
  type: Linear
  dropout: 0.05

optimizer_embedded:
  type: Adam
  lr: 0.00167934377193017
  weight_decay: 1.0272188756302E-05

# Pretext Task (SimCLR)
pretext_encoder:
  type: Resnet18
  feature_dim: 128

pretext_optimizer:
  type: SGD
  lr: 0.4
  nesterov: False
  weight_decay: 0.0001
  momentum: 0.9
  lr_scheduler: cosine
  lr_scheduler_decay: 0.1

pretext_clr_loss:
  temperature: 0.1

pretext_training:
  batch_size: 512
  epochs: 500
