dataset:
  budget: 400
  initial_points_per_class: 1
  classifier_batch_size: 64
  validation_split: 0.01

classifier:
  # Copied from TopV2
  type: BiLSTM
  dropout: 0.05

optimizer:
  # Copied from TopV2
  type: NAdam
  lr: 0.00155412888113029
  weight_decay: 1.77805840656653E-07

dataset_embedded:
  encoder_checkpoint: "Not supported"
