# Normal Classification
dataset:
  budget: 100
  initial_points_per_class: 1
  classifier_batch_size: 32
  validation_split: 0.2

classifier:
  type: Linear

optimizer:
  type: NAdam
  lr: 0.001
  weight_decay: 0.0

dataset_embedded:
  encoder_checkpoint: NotImplemented
